telethon:
    BINANCE_API_KEY: VQbcC14U1eO6WFOaKGKYOyGKmv4060eSqztuH7QpHofYqrmXTbeEZuJxMyIzwlx8
    BINANCE_SECRET_KEY: gcILb7szr3sEOWK3gldPGU4VY3PE3ZJjxS6IGh0b2rbLIpDiV6Zf9B1HbKNDDEoE
    TELEGRAM_BOT_TOKEN_Cr4FundingRate_Bot: 5468672646:AAGrnJblpDaOlVpJb5Gv0lgA-51Ggwrh64Y
    TELEGRAM_BOT_TOKEN_coinr4Bot: 5667331155:AAFCEHb5XKoUO5NvWintUnQk8R_xSCllaVE
    TELEGRAM_CHAT_ID_CryptoHawk-Bot-Forward_Signal: -831416007
    TELEGRAM_CHAT_ID_Test_bot: -1001787987662
    TELEGRAM_CHAT_ID_The_Bull: -1001284332848
    TELEGRAM_CHAT_ID_Rose: -1001429238571
    TELEGRAM_CHAT_ID_coach: -1001415616482
    TELEGRAM_CHAT_ID_klondike: -1001401152082
    api_id: 28206423
    api_hash: 61a64a5d9e5dbedaba7c55b02b29c101

